apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd

spec:
  source:
    helm:
      valuesObject:
        global:
          clusterName: az-2
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "az-2-cluster"
              advertise: "nats.az-2.dramisinfo.com:7222"
              gateways:
                - name: "az-1-cluster"
                  url: "nats://nats.az-1.dramisinfo.com:7222"