apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - ../../base

patches:
  - path: patches/core-config.yaml
  - path: patches/argo-ingress.yaml
  - path: patches/platform-core.yaml
