apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.1.0"
    targetRevision: v1.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true