apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 8.4.4
    chart: grafana
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.dev.dramisinfo.com
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.dev.dramisinfo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
