apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: ngnix
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://helm.nginx.com/stable"
    targetRevision: 1.3.1
    chart: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
