# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   annotations:
#     argocd.argoproj.io/sync-options: Prune=false
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   destination:
#     namespace: telemetry
#     server: "https://kubernetes.default.svc"
#   project: default
#   source:
#     repoURL: "https://prometheus-community.github.io/helm-charts"
#     targetRevision: 60.5.0
#     chart: kube-prometheus-stack
#     helm:
#       valuesObject:
#         kubeStateMetrics:
#           enabled: false
#         defaultRules:
#           create: false
#         alertmanager:
#           enabled: false
#         grafana:
#           enabled: false
#         nodeExporter:
#           enabled: false
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - SkipHooks=true
#       - Timeout=600
#       - Validate=false
#       - Wait=true
#       - PruneEmpty=true
