apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: OLM
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: operator-lifecycle-manager
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://stefanprodan.github.io/podinfo"
    targetRevision: main
    path: controller-config/olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
