apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://stefanprodan.github.io/podinfo"
    targetRevision: "*"
    chart: podinfo
    helm:
      valuesObject:
        replicaCount: 6
        service:
          type: LoadBalancer

      #   ingress:
      #     enabled: true
      #     className: nginx
      #     annotations:
      #       kubernetes.io/ingress.class: nginx
      #       cert-manager.io/cluster-issuer: letsencrypt-prod
      #       nginx.ingress.kubernetes.io/rewrite-target: /
      #     hosts:
      #       - host: patate.dev.dramisinfo.com
      #         paths:
      #           - path: /
      #             pathType: Prefix
      #     tls:
      #       - secretName: podinfo-tls
      #         hosts:
      #           - patate.dev.dramisinfo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-2
  namespace: podinfo
spec:
  ports:
    - name: http
      port: 9898
      targetPort: 9898
  selector:
    app: podinfo
  type: LoadBalancer
