apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 13.6.0
    chart: prometheus
    helm:
      valuesObject:
        server:
          service:
            type: LoadBalancer
    # helm:
    #   valuesObject:
    #     server:
    #       ingress:
    #         enabled: true
    #         annotations:
    #           kubernetes.io/ingress.class: nginx
    #           cert-manager.io/cluster-issuer: letsencrypt-prod
    #           nginx.ingress.kubernetes.io/rewrite-target: /
    #         hosts:
    #           - host: prometheus.dev.dramisinfo.com
    #             paths:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
