apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.10.0"
    helm:
      valuesObject:
        global:
          clusterName: az-1
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "az-1-cluster"
              advertise: "nats.az-1.dramisinfo.com:7222"
              gateways:
                - name: "az-2-cluster"
                  url: "nats://nats.az-2.dramisinfo.com:7222"
