apiVersion: v1
kind: Ingress
metadata:
  name: grafana
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.dev.dramisinfo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
        name: grafana
        port:
          number: 3000
    tls:
    - hosts:
      - grafana.dev.dramisinfo.com
      secretName: grafana-tls  