apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 8.4.4
    chart: grafana
    helm:
      valuesObject:
        adminPassword: admin
        persistence:
          enabled: true
          size: 5Gi
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-platform
          hosts:
            - grafana.platform.dramisinfo.com
          tls:
            - secretName: grafana-platform-tls
              hosts:
                - grafana.platform.dramisinfo.com
        # Anonymous access configuration
        grafana.ini:
          auth.anonymous:
            enabled: true
            org_role: Viewer
          auth:
            disable_login_form: true

        # Preconfigured datasources for Prometheus
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true

        # Dashboards configuration
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "kubernetes"
                orgId: 1
                folder: "Kubernetes"
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/kubernetes

        # Predefined dashboards for cluster monitoring
        dashboards:
          kubernetes:
            k8s-cluster-overview:
              gnetId: 15757 # Kubernetes Cluster Overview
              revision: 1
              datasource: Prometheus
            k8s-capacity:
              gnetId: 5228
              revision: 6
              datasource: Prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
