apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: "1.x"
    chart: harbor
    helm:
      valuesObject:
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
          ingress:
            hosts:
              core: harbor.platform.dramisinfo.com
              notary: notary.platform.dramisinfo.com
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-platform
            tls:
              - hosts:
                  - harbor.platform.dramisinfo.com
                secretName: harbor-tls

        externalURL: https://harbor.platform.dramisinfo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - ApplyOutOfSyncOnly=true
      - Force=true
