apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: "1.15.0"
    chart: harbor
    helm:
      valuesObject:
        externalURL: https://harbor.platform.dramisinfo.com
        expose:
          ingress:
            className: nginx
            tls:
              enabled: true
              certSource: secret
              secret:
                secretName: harbor-ingress
            hosts:
              core: harbor.platform.dramisinfo.com
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - ApplyOutOfSyncOnly=true
      - Force=true
