apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  project: default
  source:
    chart: artifactory-oss
    repoURL: https://charts.jfrog.io
    targetRevision: "107.111.4"
    helm:
      values: |
        artifactory:
          nginx:
            enabled: false
          persistence:
            enabled: true
            size: 50Gi
          ingress:
            enabled: true
            defaultBackend:
              enabled: true
            hosts:
              - artifactory.platform.dramisinfo.com
            className: nginx
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/ssl-redirect: "true" 
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              cert-manager.io/cluster-issuer: letsencrypt-platform
            tls:
              - secretName: artifactory-tls
                hosts:
                  - artifactory.platform.dramisinfo.com
  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - ApplyOutOfSyncOnly=true
      - Force=true
