apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - cluster-issuer.yaml
  - ingress-controller-nginx.yaml
  - harbor.yaml
  - vault.yaml
  - jfrog-artifactory.yaml
  # - test-helm.yaml
