apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - cert-manager.yaml
  - ingress-controller-nginx.yaml
  - cluster-issuer.yaml
  - harbor.yaml
  - vault.yaml

  # - test-helm.yaml
