apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - ../../base
  # - cert-manager.yaml
  # - cluster-issuer.yaml
  # - ingress-controller-nginx.yaml
  - harbor.yaml
  - vault.yaml

patches:
  - path: patches/platform-core.yaml


  # - test-helm.yaml
