apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - ../../base
  - harbor.yaml
  - vault.yaml
  # - cluster-issuer.yaml
  # - test-helm.yaml

patches:
  - path: patches/platform-core.yaml
