apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - cluster-issuer.yaml
  - ingress-controller-nginx.yaml
  - grafana-application.yaml
  - prometheus-application.yaml
  # - jfrog-artifactory.yaml
  # - ollama-application.yaml
  # - ollama-model-puller.yaml
  # - open-webui-application.yaml
  # - n8n-application.yaml
  # - gitea-application.yaml
