apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - cluster-issuer.yaml
  - ingress-controller-nginx.yaml
  - n8n-application.yaml
  - ollama-application.yaml
  - ollama-model-puller.yaml
  - open-webui-application.yaml
  # - vault.yaml
  # - harbor.yaml
  # - jfrog-artifactory.yaml
  # - test-helm.yaml
