apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://open-webui.github.io/helm-charts
    targetRevision: 6.1.0
    helm:
      values: |
        replicaCount: 1
        ollama:
          enabled: false
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-platform
          host: openwebui.platform.dramisinfo.com
          tls: true
        persistence:
          enabled: true
          size: 2Gi
        ollamaUrls:
          - "http://ollama.ollama.svc.cluster.local:11434"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
