apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 25.26.0
    chart: prometheus
    helm:
      valuesObject:
        rbac:
          create: true
        serviceAccounts:
          server:
            create: true
            name: prometheus-server
            annotations: {}
          alertmanager:
            create: true
            name: ""
          pushgateway:
            create: true
            name: ""
          node-exporter:
            create: true
            name: ""
        server:
          persistentVolume:
            enabled: true
            size: 10Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-platform
              nginx.ingress.kubernetes.io/ssl-passthrough: "false"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - prometheus.platform.dramisinfo.com
            tls:
              - hosts:
                  - prometheus.platform.dramisinfo.com
                secretName: prometheus-tls
          # Ensure the service name is correctly set
          service:
            annotations: {}
            labels: {}
            clusterIP: ""
            port: 80
            targetPort: 9090
            nameOverride: prometheus-server
            type: ClusterIP
        # Configure kube-state-metrics for additional workload metrics
        kube-state-metrics:
          enabled: true
        # Configure Prometheus to collect from the kubelet with proper auth
        extraScrapeConfigs: |
          - job_name: 'kubernetes-nodes'
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            scheme: https
          - job_name: 'kubernetes-kubelet'
            honor_labels: true
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__address__]
                regex: (.+):(.+)
                target_label: __address__
                replacement: ${1}:10250
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            scheme: https
            metrics_path: /metrics
        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: prometheus
                static_configs:
                  - targets:
                      - localhost:9090
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - action: keep
                    regex: true
                    source_labels:
                      - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                  - action: replace
                    regex: (.+)
                    source_labels:
                      - __meta_kubernetes_pod_annotation_prometheus_io_path
                    target_label: __metrics_path__
                  - action: replace
                    regex: ([^:]+)(?::\d+)?;(\d+)
                    replacement: $1:$2
                    source_labels:
                      - __address__
                      - __meta_kubernetes_pod_annotation_prometheus_io_port
                    target_label: __address__
                  - action: labelmap
                    regex: __meta_kubernetes_pod_label_(.+)
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: kubernetes_namespace
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_name
                    target_label: kubernetes_pod_name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
