apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          certManager:
            workloadIdentity:
              clientId: "b97c8546-c26e-47d1-835a-a905a2777896"
