apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          crossplane:
            workloadIdentity:
              clientId: "9e4c7e33-94ad-4b38-ad30-d842803b3cb1"
