apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          crossplane:
            workloadIdentity:
              clientId: "9ab62d35-8bfa-4a4e-8955-499985b9aadd"
