apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          crossplane:
            workloadIdentity:
              clientId: "465167d9-55a8-4a1d-9976-ee8f5567a710"
