apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/DramisInfo
  githubAppId: "1052895"  # Replace with your actual GitHub App ID
  githubAppInstallationId: "55895523"  # Replace with your actual Installation ID
