apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd

spec:
  source:
    helm:
      valuesObject:
        global:
          clusterName: cace-1-dev
        bootstrap:
          monitoring:
            enabled: true
          nats:
            enabled: false
            gateway:
              enabled: true
              name: "cace-1-dev-cluster"
              advertise: "nats.cace-1-dev.dramisinfo.com:7222"
              gateways:
                - name: "cace-2-dev-cluster"
                  url: "nats://nats.cace-2-dev.dramisinfo.com:7222"
          gatekeeper:
            policies:
              excludedNamespaces:
                - kube-system
                - gatekeeper-system
                - cert-manager
                - istio-system
                - ingress-nginx
                - argocd
                - azure-arc
                - arc-workload-identity
  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
