apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.12.0"
    helm:
      valuesObject:
        global:
          clusterName: cace-1-dev
        bootstrap:
          opslevel:
            enabled: false
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "cace-1-dev-cluster"
              advertise: "nats.cace-1-dev.dramisinfo.com:7222"
              gateways:
                - name: "cace-2-dev-cluster"
                  url: "nats://nats.cace-2-dev.dramisinfo.com:7222"
