apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.17"
    helm:
      valuesObject:
        global:
          clusterName: cace-1-dev-cluster
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: false
              name: "cace-1-dev"
              advertise: "nats.cace-1-dev.dramisinfo.com:7222"
              # gateways:
              #   - name: "cace-2-dev"
              #     url: "nats://nats.cace-2-dev.dramisinfo.com:7222"
