apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd

spec:
  source:
    targetRevision: "v0.16.0"
    helm:
      valuesObject:
        global:
          clusterName: cace-1-dev
        bootstrap:
          prometheus:
            enabled: true
          grafana:
            enabled: true
            # Install GitHub grafana plugin and provision a GitHub datasource
            plugins:
              # plugin IDs or full download URLs are accepted. Example plugin id below.
              - grafana-github-datasource
            pluginsPreinstallSync: true
            # NOTE: Datasources can be added later; currently only the plugin is enabled
          loki:
            enabled: true
          nats:
            enabled: true
            gateway:
              enabled: false
              name: "cace-1-dev-cluster"
              advertise: "nats.cace-1-dev.dramisinfo.com:7222"
              gateways:
                - name: "cace-2-dev-cluster"
                  url: "nats://nats.cace-2-dev.dramisinfo.com:7222"
