apiVersion: platform.dramisinfo.com/v1alpha1
kind: XCertManagerIdentity
metadata:
  name: cace-1-dev-certmanager
spec:
  clusterName: cace-1-dev
  resourceGroup: rg-cace-1-dev
  location: canadacentral
  dnsRoleScope: /subscriptions/c1d22d5c-418b-4bd9-ba23-5e806c376b56/resourceGroups/rg-dns
  oidcIssuer: https://canada.oic.prod-arc.azure.com/b66f9c3b-d384-4932-92fd-444edca3620f/c861afb0-94b0-4778-a429-92d211c06bc2/
  identityName: umi-cace-1-dev-certmanager
