apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    team: team-alpha
    environment: dev
    managed-by: platform-team
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: team-alpha
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: team-alpha
spec:
  limits:
  - max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 10m
      memory: 16Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
