apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha-agentic-system
  labels:
    team: team-alpha
    environment: dev
    managed-by: platform-team
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: team-alpha-agentic-system
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 4Gi
    limits.cpu: 4000m
    limits.memory: 8Gi
    persistentvolumeclaims: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: team-alpha-agentic-system
spec:
  limits:
    - max:
        cpu: 4000m
        memory: 2Gi
      min:
        cpu: 10m
        memory: 16Mi
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
