apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/cluster-issuer.yaml
    target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
      name: letsencrypt-base
      namespace: cert-manager
