apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: v1.22.3
    chart: base
    helm:
      valuesObject:
        defaultRevision: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[].failurePolicy'
