apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.5.0"
    helm:
      valuesObject:
        global:
          clusterName: azure-1
        bootstrap:
          crossplane:
            enabled: false
          terraformOperator:
            enabled: false
