apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/DramisInfo/test-application.git"
    targetRevision: HEAD
    path: "overlays/development"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: test-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
