apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentic-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: agentic-management
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/DramisInfo/agentic-management"
    targetRevision: HEAD
    path: charts/agentic-platform
    helm:
      valuesObject:
        # KEDA Configuration
        keda:
          enabled: true
        
        # NATS Configuration - using existing cluster NATS
        nats:
          enabled: false  # Disable chart NATS installation
          
        # Environment-specific configuration for dev
        global:
          environment: dev
          # External NATS configuration
          nats:
            url: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
            user: "app"
            password: "nats-app-dev"
          
        # Controller configuration
        agenticPlatformController:
          enabled: true
          image:
            repository: ghcr.io/dramisinfo/agentic-management/agentic-platform-controller
            tag: pr-63
          replicas: 1
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NATS_URL
              value: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
            - name: NATS_USER
              value: "app"
            - name: NATS_PASSWORD
              value: "nats-app-dev"
              
        # Configuration Manager configuration
        configurationManager:
          image:
            repository: ghcr.io/dramisinfo/agentic-management/configuration-manager
            tag: pr-63
          env:
            NATS_URL: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
            NATS_USER: "app"
            NATS_PASSWORD: "nats-app-dev"          
              
        # NATS Gateway configuration
        natsGateway:
          image:
            repository: ghcr.io/dramisinfo/agentic-management/nats-gateway
            tag: pr-63
          env:
            - name: NATS_URL
              value: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
            - name: NATS_USER
              value: "app"
            - name: NATS_PASSWORD
              value: "nats-app-dev"
              
        # UI configuration
        ui:
          enabled: true
          image:
            repository: ghcr.io/dramisinfo/agentic-management/ui
            tag: pr-63
          replicas: 1
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-platform
            hosts:
              - host: agentic-management.cace-1-dev.dramisinfo.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: agentic-management-cace-1-dev-tls
                hosts:
                  - agentic-management.cace-1-dev.dramisinfo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
