apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentic-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: agentic-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/DramisInfo/agentic-management"
    targetRevision: HEAD
    path: charts/agentic-platform
    helm:
      valuesObject:
        # KEDA Configuration
        keda:
          enabled: true
        testConfigurations:
          enabled: true        
        # NATS Configuration - using existing cluster NATS
        nats:
          enabled: false  # Disable chart NATS installation
          endpoint: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
        nack:
          enabled: false
          jetstream:
            stream:
              # Cluster placement configuration for multi-node NATS clusters
              placement:
                cluster: "cace-1-dev-cluster"
          
        # Environment-specific configuration for dev
        global:
          environment: dev
          # External NATS configuration
          nats:
            url: "nats://nats-cace-1-dev.nats.svc.cluster.local:4222"
            user: "app"
            password: "nats-app-dev"
        agentRunner:
          sk:
            enabled: true
            image:
              repository: ghcr.io/dramisinfo/agentic-management/agent-runner-sk
              tag: v1.0.14
            scaling:
              nats:
                serverEndpoint: "nats-cace-1-dev-headless.nats.svc.cluster.local:8222"
          agno:
            enabled: true
            image:
              repository: ghcr.io/dramisinfo/agentic-management/agent-runner-agno
              tag: v1.0.14
            scaling:
              nats:
                serverEndpoint: "nats-cace-1-dev-headless.nats.svc.cluster.local:8222"
            crew:
              primary:
                scaling:
                  successfulJobsHistoryLimit: 1
              member:
                scaling:
                  successfulJobsHistoryLimit: 1  
        # Controller configuration
        agenticPlatformController:
          enabled: true
          image:
            repository: ghcr.io/dramisinfo/agentic-management/agentic-platform-controller
            tag: v1.0.14
          replicas: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              
        # Configuration Manager configuration
        configurationManager:
          enabled: true
          replicaCount: 3
          image:
            repository: ghcr.io/dramisinfo/agentic-management/configuration-manager
            tag: v1.0.14
          env:
            NATS_USER: "app"
            NATS_PASSWORD: "nats-app-dev"          
              
        # NATS Gateway configuration
        natsGateway:
          image:
            repository: ghcr.io/dramisinfo/agentic-management/nats-gateway
            tag: v1.0.14
          replicaCount: 3
          env:
            NATS_USER: "app"
            NATS_PASSWORD: "nats-app-dev"
              
        # UI configuration
        ui:
          enabled: true
          image:
            repository: ghcr.io/dramisinfo/agentic-management/ui
            tag: v1.0.14
          replicaCount: 3

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-platform
          host: agentic-system.cace-1-dev.dramisinfo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
