apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-50"  # Deploy before main kagent application
spec:
  destination:
    namespace: kagent
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "ghcr.io/kagent-dev/kagent/helm/kagent-crds"
    chart: kagent-crds
    targetRevision: "0.6.14"  # Latest version as of documentation
    helm:
      valuesObject: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ServerSideApply=true
      - Replace=true