apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-25"  # Deploy before kagent but after CRDs
spec:
  destination:
    namespace: kagent
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/DramisInfo/platform-tools"
    targetRevision: HEAD
    path: overlays/cace-1-dev/kagent-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true