apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.3"
    helm:
      valuesObject:
        global:
          clusterName: dev
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "dev-cluster"
              advertise: "nats.dev.dramisinfo.com:7222"
              gateways:
                - name: "staging-cluster"
                  urls: 
                    - "nats://nats.staging.dramisinfo.com:7222"
