apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.2"
    helm:
      valuesObject:
        global:
          clusterName: dev
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "dev-cluster"
              advertise: "nats.dev.dramisinfo.com:7222"
          # crossplane:
          #   enabled: true
          # atlas:
          #   enabled: true
          # terraformOperator:
          #   enabled: true

          # prometheus:
          #   enabled: true
          # grafana:
          #   enabled: true
          # loki:
          #   enabled: true
