apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.1"
    helm:
      valuesObject:
        global:
          clusterName: dev
        bootstrap:
          # crossplane:
          #   enabled: true
          # atlas:
          #   enabled: true
          # terraformOperator:
          #   enabled: true
          # externalSecretOperator:
          #   enabled: true
          # prometheus:
          #   enabled: true
          # grafana:
          #   enabled: true
          # loki:
          #   enabled: true
