apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "0.3.10"
    helm:
      valuesObject:
        cert-manager.io/cluster-issuer: vault-dev
