apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "0.4.8"
    helm:
      valuesObject:
        global:
          clusterName: dev
