apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "0.2.50"
    helm:
      valuesObject:
        global:
          clusterName: dev
        bootstrap:
          crossplane:
            enabled: false
          atlas:
            enabled: false
          terraformOperator:
            enabled: false
          externalSecretOperator:
            enabled: false
          prometheus:
            enabled: true
          grafana:
            enabled: true
          loki:
            enabled: true
