apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "0.4.2"
    helm:
      valuesObject:
        clusterName: dev
