apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-github-collector
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: otel-github-collector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - monitoring
