# IMPORTANT: Updated with your actual Azure OpenAI API key
# Using API key authentication (Azure AD token not needed)

apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secret
  namespace: kagent
type: Opaque
data:
  # Your actual base64-encoded Azure OpenAI API key
  api-key: M052TWV3ZTJENlhUU01MMTBNT3UxZDhZUEUxTkx6djdOdEFVVXBqdGdPVW54NzhDOUdCNEpRUUo5OUJIQUNIWUh2NlhKM3czQUFBQUFDT0dncEgz