# ModelConfig for Azure OpenAI
# Configured with your actual Azure OpenAI settings

apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: azure-default-model-config
  namespace: kagent
spec:
  apiKeySecret: azure-openai-secret
  apiKeySecretKey: api-key
  model: gpt-4o-mini  # Using gpt-4o-mini to match your deployment
  provider: AzureOpenAI
  azureOpenAI:
    # Your actual Azure OpenAI endpoint
    azureEndpoint: "https://fmsim-mduyvedu-eastus2.openai.azure.com"
    
    # Your specified API version
    apiVersion: "2025-01-01-preview"
    
    # Your actual deployment name
    azureDeployment: "gpt-4.1-mini"