apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  namespace: observability
type: Opaque
stringData:
  github_app_id: "REPLACE_WITH_APP_ID"
  github_installation_id: "REPLACE_WITH_INSTALLATION_ID"
  github_private_key_pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_WITH_YOUR_PRIVATE_KEY_CONTENT
    -----END RSA PRIVATE KEY-----
  github_webhook_secret: "REPLACE_WITH_WEBHOOK_SECRET"
