apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.11"
    helm:
      valuesObject:
        global:
          clusterName: staging
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "staging-cluster"
              advertise: "nats.staging.dramisinfo.com:7222"
              # gateways:
              #   - name: "dev-cluster"
              #     url: "nats://nats.dev.dramisinfo.com:7222"