apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.2"
    helm:
      valuesObject:
        global:
          clusterName: staging
        bootstrap:
          externalSecretOperator:
            enabled: true