apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "0.2.34"
    helm:
      valuesObject:
        global:
          clusterName: staging
        bootstrap:
          crossplane:
            enabled: true
          atlas:
            enabled: false
