apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - ../../base
  - agentic-management-application-1.yaml  
  # - agentic-management-application-2.yaml  

patches:
  - path: patches/platform-core.yaml
