---
- name: Merge notification
  hosts: master
  become: true

  tasks:
    - name: Refresh
      block:
        - name: Get ArgoCD applications
          shell: kubectl get applications -n argocd -o jsonpath='{.items[*].metadata.name}'
          register: argocd_applications
          when: true

        - name: Refresh ArgoCD applications
          shell: kubectl patch application {{ item }} -n argocd --type merge -p '{"operation":{"initiatedBy":{"username":"admin"},"refresh":"normal"}}'
          check_mode: no
          changed_when: true
          with_items: "{{ argocd_applications.stdout.split(' ') }}"
          when: true

        - name: Completed
          debug:
            msg: "ArgoCD refresh initiated"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      when: true
