---
- name: Merge notification
  hosts: master
  become: true

  tasks:
    - name: Sync ArgoCD
      shell: kubectl patch application platform-tools -n argocd --type merge -p '{"operation":{"initiatedBy":{"username":"admin"},"sync":{"syncStrategy":{"hook":{}}}}}'
      check_mode: no
      changed_when: true

    - name: Completed
      debug:
        msg: "ArgoCD sync initiated"
