apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    namespace: test-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/DramisInfo/platform-helm.git
    targetRevision: "HEAD"
    path: platform-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - Validate=false
      - Prune=true
