apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: kiali
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: kiali
    ingress:
      enabled: true
      class_name: nginx
      override_yaml:
        metadata:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/secure-backends: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        spec:
          rules:
          - host: kiali.dev.dramisinfo.com
            http:
              paths:
              - path: "/kiali"
                pathType: Prefix
                backend:
                  service:
                    name: "kiali"
                    port:
                      number: 20001
          tls:
          - hosts:
            - kiali.dev.dramisinfo.com
            secretName: kiali-tls
  auth:
    strategy: anonymous
