apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: kiali
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: kiali
    ingress:
      enabled: true
      override_yaml:
        metadata:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/secure-backends: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        spec:
          ingressClassName: nginx
          rules:
          - host: istio.dev.dramisinfo.com
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: "kiali"
                    port:
                      number: 20001
          tls:
          - hosts:
            - istio.dev.dramisinfo.com
            secretName: istio-tls
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      # Prometheus service name is "metrics" and is in the "telemetry" namespace
      url: "http://prometheus-server.monitoring/"    
