apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: kiali
  name: kiali
spec:
  istio_namespace: istio-system
  deployment:
    namespace: kiali
    ingress:
      enabled: true
      override_yaml:
        metadata:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/secure-backends: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        spec:
          ingressClassName: nginx
          rules:
            - host: istio.dev.appelatous.com
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: "kiali"
                        port:
                          number: 20001
          tls:
            - hosts:
                - istio.dev.appelatous.com
              secretName: istio-tls
  auth:
    strategy: anonymous
  # external_services:
  #   prometheus:
  #     # Prometheus service name is "metrics" and is in the "telemetry" namespace
  #     url: "http://prometheus-server.monitoring/"
  #   tracing:
  #     # Enabled by default. Kiali will anyway fallback to disabled if
  #     # Jaeger is unreachable.
  #     enabled: true
  #     # Jaeger service name is "tracing" and is in the "telemetry" namespace.
  #     # Make sure the URL you provide corresponds to the non-GRPC enabled endpoint
  #     # if you set "use_grpc" to false.
  #     in_cluster_url: "http://jaeger-query.monitoring:16685/jaeger"
  #   grafana:
  #     enabled: true
  #     # Grafana service name is "grafana" and is in the "telemetry" namespace.
  #     in_cluster_url: 'http://grafana.monitoring/'
  #     # Public facing URL of Grafana
  #     url: 'https://grafana.dev.appelatous.com'
  #     dashboards:
  #     - name: "Istio Service Dashboard"
  #       variables:
  #         namespace: "var-namespace"
  #         service: "var-service"
  #     - name: "Istio Workload Dashboard"
  #       variables:
  #         namespace: "var-namespace"
  #         workload: "var-workload"
  #     - name: "Istio Mesh Dashboard"
  #     - name: "Istio Control Plane Dashboard"
  #     - name: "Istio Performance Dashboard"
  #     - name: "Istio Wasm Extension Dashboard"
