apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          certManager:
            workloadIdentity:
              clientId: "b61e84a5-512e-423d-a614-79e7b6974241"
