apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          crossplane:
            workloadIdentity:
              clientId: "5d0807c0-0fd5-45a6-964b-235275aa1523"
