apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        bootstrap:
          crossplane:
            workloadIdentity:
              clientId: "ca026fac-a239-495d-bc8e-bb68fd2b1753"
