apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  source:
    targetRevision: "v0.9.13"
    helm:
      valuesObject:
        global:
          clusterName: cace-2-dev
        bootstrap:
          nats:
            enabled: true
            gateway:
              enabled: true
              name: "cace-2-dev"
              advertise: "nats.cace-2-dev.dramisinfo.com:7222"
              gateways:
                - name: "cace-1-dev"
                  url: "nats://nats.cace-1-dev.dramisinfo.com:7222"