name: Notify ArgoCD
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --tags "sync-argocd" --become-user ubuntu
