name: Notify ArgoCD
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Sync ArgoCD
        run: ansible-playbook ansible/playbook.yml -i ansible/inventory.yml --tags "sync-argocd"
