name: Notify ArgoCD
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Sync ArgoCD
        run: |
          ssh ubuntu@192.168.2.12 'kubectl patch application platform-tools -n argocd --type merge -p ''{"operation":{"initiatedBy":{"username":"admin"},"sync":{"syncStrategy":{"hook":{}}}}}'''
