name: Notify ArgoCD
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Sync ArgoCD
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --tags "sync-argocd" --become-user ubuntu
